name: Build Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Theos
      uses: Randomblock1/theos-action@v1
      
    - name: Build Package
      run: |
        make package THEOS_PACKAGE_SCHEME=rootless > build.log 2>&1
        
    - name: Upload Log to File.io on Failure
      if: failure()
      run: |
        LINK=$(curl -s -F "file=@build.log" https://file.io | grep -o '"link":"[^"]*' | cut -d'"' -f4)
        echo "::error file=build.log,line=1::Build failed. Download log here: $LINK"
        cat build.log
        exit 1
        
    - name: Upload DEB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FreeFireMaxESP-deb
        path: packages/*.deb
